import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";

import { RootClient } from "./rootClient";
import { FormStoreProvider } from "@/domains/core/form/data/FormStoreProvider";

const geistSans = localFont({
  src: "../../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "ATLAS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FormStoreProvider>{children}</FormStoreProvider>

        <RootClient />
        {/* <Toaster /> */}
      </body>
    </html>
  );
}
