import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";

import { FormStoreProvider } from "@/domains/shared/form/data/FormStoreProvider";
import { init } from "@/services/init";
import { Toaster } from "@/components/ui/toaster";
import { cookies } from "next/headers";
import { ConfigService } from "@/services/ConfigService";
import { AuthService } from "@/services/AuthService";
import { AuthStoreProvider } from "@/domains/login/data/AuthStoreProvider";
import { LoadingComponent } from "@/components/ui/loading";

if (process.env.NEXT_RUNTIME === "nodejs") {
  // init();
}

const geistSans = localFont({
  src: "../../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const preLoad = async () => {
  await init();

  // await AuthService.isValidSession();
};

export const metadata: Metadata = {
  title: "ATLAS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  preLoad();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthStoreProvider>
          <FormStoreProvider>
            {children}
            <LoadingComponent />
          </FormStoreProvider>
        </AuthStoreProvider>

        <Toaster />
      </body>
    </html>
  );
}
