import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "../globals.css";

// import { init } from "@/services/init";

export const metadata: Metadata = {
  title: "ATLASHOME",
  description: "Generated by create next app",
};

export default function HubLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // init();
  return (
    <div className="flex flex-row w-screen h-screen">
      <div className="w-[300px] border-r-4 bg-primary"></div>
      <div className="flex-auto">{children}</div>
    </div>
  );
}
